### ISSUE TITLE
refactor: DefaultMusicRepository의 이름 변경

### ISSUE THREAD

**Issue by windowcow** [boostcampwm-2024/iOS06-molio#56]
## 1. 배경
```swift
    // DefaultMusicRepository.swift

    func fetchMusics(genres: [String]) async throws -> [RandomMusic] {
        let musicFilter = MusicFilter(genres: genres)
        let isrcs = try await spotifyAPIService.fetchRecommendedMusicISRCs(musicFilter: musicFilter)

        return try await withThrowingTaskGroup(of: RandomMusic?.self) { group in
            var musics: [RandomMusic] = []
            
            for isrc in isrcs {
                group.addTask {
                    return await musicKitService.getMusic(with: isrc)
                }
            }
            
            for try await music in group {
                if let music {
                    musics.append(music)
                }
            }
            
            return musics
        }
    }

```

### 1. DefaultMusicRepository의 이름을 `RecommendedMusicRepository`나 `GetRecommendedRandomMusicUseCase`로 이름 바꾸기
> `DefaultMusicRepository`보다는 `GetRecommendedRandomMusicUseCase`가 적절해보인다고 생각했지만
레포지토리는 데이터의 접근, 저장을 추상화하는 역할을 한다는 면에서 DefaultMusicRepository도 나쁘진 않다.

현재 Repository의 이름은 부적절하다고 느껴집니다.
현재 덱에서 랜덤 노래들을 받아오기 위해 사용하는 객체이고 유즈케이스로 사용하는 편이 더 좋다고 생각됩니다.

원래 레포지토리의 역할은 어떤 데이터 (playlist들)을 받아 올 때 그 데이터를 어디서 받아오는지 모르게끔 추상화시킨다는 것이라고 생각합니다.
이 경우에는 그런 추상화보다는 비즈니스 로직만을 담당한다는 점에서 UseCase라고 생각되는데 어떻게 생각하시나요?

**Comment by kybeen** [comment]
창우님 말씀대로 유즈케이스가 담당해야 하는 역할은 맞다고 생각합니다.

근데 지금 프로젝트에 `SpotifyRepository`도 있고, `FetchRecommendedSongsUseCase`라는 객체도 있는데 사용하지 않는 것 같네요.
피그마 의존성 그래프에서도 보이지가 않는데 이거 제가 만들었나요 혹시..?
관련 역할을 이 객체들로 옮기거나, 만들어놓고 사용 안하고 있는 객체는 만든 사람이 정리를 좀 해야할 것 같습니다.

**Comment by windowcow** [comment]
지금 정리 PR 한번 만들어서 올리겠습니다!!

**Comment by alstn38** [comment]
DefaultMusicRepository의 경우 덱에서 랜덤 노래를 받아오기 위해 사용하고 있습니다.
그리고, 이미 이와 같은 것을 수행하기 위해 DefaultFetchMusicsUseCase가 있는 것으로 알고 있습니다.
DefaultMusicRepository의 이름을 usecase로 변경하게 되고 도메인 영역에 있다면,
과연 도메인의 영역들이 네트워크 Service를 알아야하는지에 대한 의문이 듭니다. 제가 이해한 것이 맞나요?

**Comment by windowcow** [comment]
그러게요 이미 DefaultFetchMusicsUseCase가 있다는 사실을 까먹고 있었군요!
저걸 그대로 쓰는 편이 좋을 것 같습니다 ㅎㅎ

유즈케이스 이름은 `DefaultFetchRecommendedMusicUseCase`로 변경하는 편이 좋을 것 같은데 어떻게 생각하시나요?? (프로토콜 이름도 변경해야할 것 같습니다.)

추천된 노래 말고도 데이터베이스에서 특정 플레이리스트에 저장된 노래를 가져오는 상황도 있기 때문입니다 😊

**Comment by windowcow** [comment]
> DefaultMusicRepository의 경우 덱에서 랜덤 노래를 받아오기 위해 사용하고 있습니다. 그리고, 이미 이와 같은 것을 수행하기 위해 DefaultFetchMusicsUseCase가 있는 것으로 알고 있습니다. DefaultMusicRepository의 이름을 usecase로 변경하게 되고 도메인 영역에 있다면, 과연 도메인의 영역들이 네트워크 Service를 알아야하는지에 대한 의문이 듭니다. 제가 이해한 것이 맞나요?

말씀대로 UseCase로 변경하는 경우에 서비스를 직접 알아야 하는군요!
그러면 안될 것 같습니다. 실제로 타겟을 나눴다면 분명 불가능한 경우이군요.

좋은 의견 너무 감사합니다 ㅎㅎ

**Comment by alstn38** [comment]
넵 usecase 이름 변경에 대해서는 동의합니다 !!
